services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    restart: always

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    command: ["node", "dist/worker.js"]
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    restart: on-failure
